In [4]:
import numpy as np
import matplotlib.pyplot as plt


X = np.array([

    [80,3],
    [120,3],
    [100,2],
    [150,4]

])

Y = np.array([310,390,325,530])

X_bias = np.c_[np.ones((4,1)),X]

A_saludable = X_bias.T @ X_bias
b = X_bias.T @ Y


In [17]:
pies2 = X[:,0] * 12.893

X_enfermo = np.c_[X, pies2]

X_enfermo_bias = np.c_[np.ones((4,1)), X_enfermo]

print(X_enfermo_bias)

[[1.00000e+00 8.00000e+01 3.00000e+00 1.03144e+03]
 [1.00000e+00 1.20000e+02 3.00000e+00 1.54716e+03]
 [1.00000e+00 1.00000e+02 2.00000e+00 1.28930e+03]
 [1.00000e+00 1.50000e+02 4.00000e+00 1.93395e+03]]


In [18]:
A_enfermo = X_enfermo_bias.T @ X_enfermo_bias
b = X_enfermo_bias.T @ Y


In [19]:
determinante = np.linalg.det(A_enfermo)
print(determinante)

1.711074728518716e-05


In [20]:
rango = np.linalg.matrix_rank(A_enfermo)
print(rango)

3


In [23]:
theta1 = np.linalg.inv(A_enfermo) @ b
print(theta1)

[-9.90584417e+02  5.64035088e+00  4.04385965e+01  2.50000000e-01]


In [25]:
theta2 = np.linalg.solve(A_enfermo, b)
print(theta2)


[-11.84210526  -0.74079386  40.43859649   0.25      ]
