In [19]:
import numpy as np
import matplotlib.pyplot as plt

X = np.array([
    [80,3],
    [120,3],
    [100,2],
    [150,2]
])

Y= np.array([310,390,325,530])

x_bias = np.c_[np.ones((4,1)),X]



A_saludable = x_bias.T  @ x_bias
b = x_bias.T @ Y



In [20]:
det_saludable = np.linalg.det(A_saludable)
print(det_saludable)

rango_saludable = np.linalg.matrix_rank(A_saludable)
print(rango_saludable)

8199.999999999955
3


In [23]:
habitaciones_doble = X[:, 1] *2
X_enfermo = np.c_[X, habitaciones_doble]
x_enfermo_bias = np.c_[np.ones((4,1)), X_enfermo]

print(x_enfermo_bias)

[[  1.  80.   3.   6.]
 [  1. 120.   3.   6.]
 [  1. 100.   2.   4.]
 [  1. 150.   2.   4.]]


In [ ]:
A_enfermo = x_enfermo_bias.T @ x_enfermo_bias
print(A_enfermo)

[[4.00e+00 4.50e+02 1.00e+01 2.00e+01]
 [4.50e+02 5.33e+04 1.10e+03 2.20e+03]
 [1.00e+01 1.10e+03 2.60e+01 5.20e+01]
 [2.00e+01 2.20e+03 5.20e+01 1.04e+02]]


In [25]:
det_enfermo = np.linalg.det(A_enfermo)
print(det_enfermo)

rango_enfermo = np.linalg.matrix_rank(A_enfermo)
print(rango_enfermo)

0.0
3
