In [4]:
import numpy as np

peliculas_features = np.array([
    [5,2],
    [1,5],
    [4,4]
])

pesos_generos = np.array([
    [1.1,0.4,0.1],
    [0.2,0.5,1.2]
])



In [6]:
print(f"Shape peliculas_features: {peliculas_features.shape}")
print(f"Shape pesp_generos: {pesos_generos.shape}")

Shape peliculas_features: (3, 2)
Shape pesp_generos: (2, 3)


In [7]:
scores_prediccion = peliculas_features @ pesos_generos

print(f"Shape de la matriz socres_predccion: {scores_prediccion.shape}")
print(f"Matriz de scores (o nive de confianza) para cada genero: {scores_prediccion}")

Shape de la matriz socres_predccion: (3, 3)
Matriz de scores (o nive de confianza) para cada genero: [[5.9 3.  2.9]
 [2.1 2.9 6.1]
 [5.2 3.6 5.2]]


In [9]:
usuarios = np.array([
    #accion, drama, ciencia ficcion, demas

    [0.9,0.2,0.1,0.8],
    [0.1,0.8,0.7,0.2],
    [0.8,0.7,0.1,0.1]

])

peliculas = np.array([
    #blade runer
    [0.8,0.1,0.1,0.9],
    #super cool
    [0.2,0.9,0.8,0.1]
])



In [11]:
print(f"Shape de matriz ususarios: {usuarios.shape}")
print(f"Shape de matriz peliculas: {peliculas.shape}")

Shape de matriz ususarios: (3, 4)
Shape de matriz peliculas: (2, 4)


In [ ]:
peliculas_trasnppuesta = peliculas.T

print(f"Shape peliculas transpuesta:{peliculas_trasnppuesta.shape}")
print(f"Peliculas transpuesta:{peliculas_trasnppuesta}")

Shape peliculas trasnpuesta:(4, 2)
Peliculas trasnpuesta:[[0.8 0.2]
 [0.1 0.9]
 [0.1 0.8]
 [0.9 0.1]]


In [16]:
similitud = usuarios @ peliculas_trasnppuesta

print(f"Similitud de entre usuarios y peliculas transpuesta: {similitud}")
print(f"Shape de similitud de entre usuarios y peliculas transpuesta: {similitud.shape}")

Similitud de entre usuarios y peliculas transpuesta: [[1.47 0.52]
 [0.41 1.32]
 [0.81 0.88]]
Shape de similitud de entre usuarios y peliculas transpuesta: (3, 2)


In [17]:
# matriz de datos de columnas 4 x filas 3 y matriz de pesos 3 columnoas x 2 filas realizar las multiplicaciones de las 2 matricies y las formas

#Matirz compaciosion peso, talla, envergadura, talla sentado, filas: usuario 1,2,3
composicion_usuariaos = np.array([

    #usuario

    [78,164,163,78],
    [65,168,167,68],
    [70,180,180,80],
])
 #matriz deportes 3 columnas peso, talla,talla sentado 2 filas, futbol, escalada 

composicion_deporte = np.array([
    [80,168,70],
    [60,180,80]
])

print(f"Shape de composicion usuariaos: {composicion_usuariaos.shape}")
print(f"Matriz de composicion usuariaos: {composicion_usuariaos}")

print(f"Shape de composicion deporte: {composicion_deporte.shape}")
print(f"Matriz de composicion deporte: {composicion_deporte}")


Shape de composicion usuariaos: (3, 4)
Matriz de composicion usuariaos: [[ 78 164 163  78]
 [ 65 168 167  68]
 [ 70 180 180  80]]
Shape de composicion deporte: (2, 3)
Matriz de composicion deporte: [[ 80 168  70]
 [ 60 180  80]]


In [21]:
composicion_deporte_trasnpuesta = composicion_deporte.T

print(composicion_deporte_trasnpuesta.shape)
print(composicion_deporte_trasnpuesta)

composicion_usuariaos_traspuesta = composicion_usuariaos.T
print(composicion_usuariaos_traspuesta.shape)
print(composicion_usuariaos_traspuesta)


(3, 2)
[[ 80  60]
 [168 180]
 [ 70  80]]
(4, 3)
[[ 78  65  70]
 [164 168 180]
 [163 167 180]
 [ 78  68  80]]


In [26]:
similitud_deportes = composicion_usuariaos_traspuesta @ composicion_deporte_trasnpuesta

print(f"Shape de la similitud entre matrices trasnpuesta  de composcion del deporte y la composicion del usuario: {similitud_deportes.shape}")
print(f"Matriz de la similitud entre matrices trasnpuesta  de composcion del deporte y la composicion del usuario: {similitud_deportes}")


Shape de la similitud entre matrices trasnpuesta  de composcion del deporte y la composicion del usuario: (4, 2)
Matriz de la similitud entre matrices trasnpuesta  de composcion del deporte y la composicion del usuario: [[22060 21980]
 [53944 54480]
 [53696 54240]
 [23264 23320]]
