In [1]:
import numpy as np
import matplotlib.pyplot as plt

calificaciones_reales = np.array([5, 2])

prediccion_modelo = np.array([4, 4])

print(calificaciones_reales)
print(prediccion_modelo)

[5 2]
[4 4]


In [4]:
error = calificaciones_reales - prediccion_modelo
print(error)

[ 1 -2]


In [5]:
porcentaje_ajuste = 0.1

ajuste = error * porcentaje_ajuste

print(ajuste)

[ 0.1 -0.2]


In [7]:
ventas_enero = np.array([
    [150,200,180],
    [120,90,100]
])

ventas_febrero = np.array([
    [130,210,80],
    [110,190,120]
])

print(ventas_enero)
print(ventas_febrero)

[[150 200 180]
 [120  90 100]]
[[130 210  80]
 [110 190 120]]


In [8]:
ventas_totales = ventas_febrero + ventas_enero

print(ventas_totales)

[[280 410 260]
 [230 280 220]]


In [9]:
bonificaciones = np.array([10,15,5])

print(ventas_enero.shape)
print(bonificaciones.shape)

(2, 3)
(3,)


In [11]:
ventas_con_bon = ventas_enero + bonificaciones
print(ventas_con_bon)

[[160 215 185]
 [130 105 105]]
