In [3]:
import numpy as np

I = np.eye(3)

print(f" {I}")

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
A = np.array([
    [1,2,3],
    [4,5,6]

])

print(A @ I)

[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
M = np.array([
    [3,1],
    [2,2]

])

In [10]:
determinate = np.linalg.det(M)

print(f"Determinate de la matriz M: {determinate:.2f}")

Determinate de la matriz M: 4.00


In [12]:
M_inversa = np.linalg.inv(M)
print(f"inversa de M {M_inversa}")

inversa de M [[ 0.5  -0.25]
 [-0.5   0.75]]


In [14]:
identidad = M @ M_inversa

print(np.round(identidad,2))

[[1. 0.]
 [0. 1.]]


In [15]:
#crear una matriz de 2 x 2 y  luego generar la determinate diferente de 0 y despues calcula la inversa


T = np.array([
    [6,8],
    [9,7]
])

print(T.shape)

(2, 2)


In [18]:
determinate_T = np.linalg.det(T)

print(f"La determinate de T es: {determinate_T:.2f}")

La determinate de T es: -30.00


In [19]:
T_inversa = np.linalg.inv(T)
print(T_inversa)

[[-0.23333333  0.26666667]
 [ 0.3        -0.2       ]]


In [20]:
identidad2 =T @ T_inversa

print(np.round(identidad2,2))

[[ 1.  0.]
 [-0.  1.]]
